# Generated by Django 2.1.1 on 2019-03-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='stk_dtl',
        ),
        migrations.AddField(
            model_name='userdata',
            name='stock_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.Stocks_Details'),
            preserve_default=False,
        ),
    ]
