# Generated by Django 2.1.1 on 2019-03-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190311_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('medi', models.CharField(max_length=30)),
                ('total', models.IntegerField()),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='stock_details',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
